#!/bin/bash

source $(dirname $0)/rpi-utils.conf

_help() {
	echo "shutdownbutton - button to trigger shutdown command"
	echo ""
	echo "usage: shutdownbutton [start|stop]"
	echo "       [start/stop the button event listener]"
}

case "$1" in
  start)
    sudo $(dirname $0)/$SCRIPTS_dir/shutdownbutton_button.sh  > /dev/null 2>&1 &
    echo "button events started"
  ;;

 	stop)
		sudo pkill -f shutdownbutton_button.sh
		echo "button events stoped"
	;;
 
  help|*)
		_help
	;;

esac