#!/bin/bash

source $(dirname $0)/rpi-utils.conf

_help() {
	echo "wifi - toggle between client and accesspoint mode"
	echo ""
	echo "usage: wifi set [default|adhoc]"
	echo "       [default: wifi interface acts as client]"
	echo "       [adhoc:   wifi interface acts as accesspoint]"
	echo "usage: wifi toggle"
	echo "       [toggle between default and adhoc]"
	echo "usage: wifi config"
	echo "       [edit wpa_supplicant.conf]"
	echo "usage: wifi status"
	echo "       [status info provided by ifconfig and iwconfig]"
	echo "usage: wifi button [start|stop]"
  echo "       [start/stop the button event listener]"
}

case "$1" in
  set)
		if [[ $2 = "default" ]] || [[ $2 = "adhoc" ]]; then 
			sudo $(dirname $0)/$SCRIPTS_dir/wifi_toggle.sh $2
		else 
			_help
		fi
    
  ;;

 	toggle)
		sudo $(dirname $0)/$SCRIPTS_dir/wifi_toggle.sh toggle
	;;
 
  config)
		sudo nano /etc/wpa_supplicant/wpa_supplicant.conf
	;;
 
 	status)
		if [[ $2 = "--mode" ]]; then
			if [ $(iwconfig $WIFI_iface | grep "Mode:" | awk -F'[: ]+' '{print $3}') = "Ad-Hoc" ]; then
				echo "adhoc"
			elif [ $(iwconfig $WIFI_iface | grep "Mode:" | awk -F'[: ]+' '{print $3}') = "Managed" ]; then
				echo "default"
			else 
				echo "unknown"
			fi
		else
			iwconfig $WIFI_iface
			ifconfig $WIFI_iface
		fi
	;;

	button)
		sudo pkill -f wifi_button.sh
		if [[ $2 = "start" ]]; then 
			sudo $(dirname $0)/$SCRIPTS_dir/wifi_button.sh > /dev/null 2>&1 &
			echo "button events started"
		elif [[ $2 = "stop" ]]; then
			echo "button events stopped"
		else 
			_help
		fi
	;;

  help|*)
		_help
	;;

esac