#!/bin/bash

source $(dirname $0)/rpi-utils.conf

_help() {
	echo "wifi - toggle between default and ad-hoc mode"
	echo ""
	echo "usage: wifi set [default|adhoc]"
	echo "       wifi toggle"
	echo "       wifi config"
	echo "       wifi status"
	echo "       wifi button [start|stop]"
}

case "$1" in
  set)
		if [[ $2 = "default" ]] || [[ $2 = "adhoc" ]]; then 
			sudo $(dirname $0)/$SCRIPTS_dir/wifi_toggle.sh $2
		else 
			_help
		fi
    
  ;;

 	toggle)
		sudo $(dirname $0)/$SCRIPTS_dir/wifi_toggle.sh toggle
	;;
 
  config)
		sudo nano /etc/wpa_supplicant/wpa_supplicant.conf
	;;
 
 	status)
		iwconfig $WIFI_iface
		ifconfig $WIFI_iface
	;;

	button)
		sudo pkill -f wifi_button.sh
		if [[ $2 = "start" ]]; then 
			sudo $(dirname $0)/$SCRIPTS_dir/wifi_button.sh > /dev/null 2>&1 &
			echo "button events started"
		elif [[ $2 = "stop" ]]; then
			echo "button events stopped"
		else 
			_help
		fi
	;;

  help|*)
		_help
	;;

esac